name: Gradle Publish

on:
  workflow_dispatch:
  release:
    types: [created]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'adopt'

    - name: Build with Gradle
      uses: gradle/gradle-build-action@v2
      with:
        arguments: build

    - name: Publish to GitHub Packages
      uses: gradle/gradle-build-action@v2
      with:
        arguments: publish
      env:
        qetzUser: ${{ secrets.REPO_USER }}
        qetzPassword: ${{ secrets.REPO_PASSWORD }}
